# Site settings
title: PRISM NAIL STUDIO
email: email@prismnailstudio.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "prismnailstudio.com" # the base hostname & protocol for your site

facebook_username: prismnailstudio
instagram_username: prismnailstudio

# Build settings
markdown: kramdown
