# Site settings
title: PRISM NAIL STUDIO
email: email@prismnailstudio.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "prismnailstudio.com" # the base hostname & protocol for your site

social:
  -title: instagram
  url: https://www.instagram.com/prismnailstudio/
  -title: facebook
  url: https://www.facebook.com/prismnailstudio/

# Build settings
markdown: kramdown
